version: '2.4'
services:
  traefik:
    image: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - "--providers.docker.constraints=Label(`traefik.environment`,`local`)"
      - '--entrypoints.web.address=:8000'
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  backend:
    build:
      context: ./backend
      target: dev
    image: crawl-app-backend
    stdin_open: false
    tty: true
    command: ./docker.dev.sh
    volumes:
      - ./backend:/app
    depends_on:
      localstack:
        condition: service_healthy
      db:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=PathPrefix(`/api/`)||PathPrefix(`/auth/`)||PathPrefix(`/admin/`)||PathPrefix(`/static/`)'
      - 'traefik.environment=local'
  frontend:
    build:
      context: ./frontend
      target: dev
    image: crawl-app-frontend
    command: ./docker.dev.sh
    volumes:
      - ./frontend:/app
      - node-data:/app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=PathPrefix(`/`)'
      - 'traefik.environment=local'
  crawler:
    build:
      context: ./go
      target: dev
      args:
        SERVICE: crawler
    image: crawl-app-crawler
    volumes:
      - ./go:/app
    depends_on:
      localstack:
        condition: service_healthy
      db:
        condition: service_healthy
    # environment:
    #   - LOG_SQL=true
  scheduler:
    build:
      context: ./go
      target: dev
      args:
        SERVICE: scheduler
    image: crawl-app-scheduler
    volumes:
      - ./go:/app
    # environment:
    #   - LOG_SQL=true
  uptimer:
    build:
      context: ./go
      target: dev
      args:
        SERVICE: uptimer
    image: crawl-app-uptimer
    volumes:
      - ./go:/app
    # environment:
    #   - LOG_SQL=true
  verifier:
    build:
      context: ./go
      target: dev
      args:
        SERVICE: verifier
    image: crawl-app-verifier
    volumes:
      - ./go:/app
    # environment:
    #   - LOG_SQL=true
  reverifier:
    build:
      context: ./go
      target: dev
      args:
        SERVICE: reverifier
    image: crawl-app-reverifier
    volumes:
      - ./go:/app
    # environment:
    #   - LOG_SQL=true
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: crawldev
    command:
      - 'postgres'
      - '-c'
      - 'listen_addresses=*'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
  localstack:
    image: localstack/localstack
    environment:
      HOSTNAME_EXTERNAL: localstack
    healthcheck:
      test: curl -f http://localhost:4566/health
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.localstack.rule=PathPrefix(`/localstack/`)'
      - 'traefik.port=49501'
      - 'traefik.environment=local'

volumes:
  db-data:
    driver: local
  node-data:
    driver: local
